#!/usr/bin/php
<?php

namespace Cli;

// use Cli;

require('vendor/autoload.php');

define('EXT', '.php');
define('DS', DIRECTORY_SEPARATOR);
define('PATH', dirname(__FILE__) . DS);

/*****************************************/
/*               CONFIG                  */
/*****************************************/

define('TEST', true);

if (TEST) {
    define('ROOT', dirname(__FILE__) . DS);
} else {
    define('ROOT', PATH . 'vendor' . DS . 'silverengine' . DS . 'cli' . DS);
}

define('TEMPLATE', ROOT . 'App' . DS . 'Templates');
define('DESTINATION', ROOT);

/*****************************************/




// var_dump(ROOT);

// exit;
define('APP', ROOT . 'src' . DS);



/**
 * @param $data
 * @param bool $param
 */
if (!function_exists('dd')) {
    function dd($data, $param = false)
    {
        if ($param) {
            var_dump('<pre>', $data, '</pre>');
        } else {
            var_dump($data);
        }
        exit();
    }
}
/**
 * @param $data
 * @param bool $param
 */
if (!function_exists('ndd')) {
    function ndd($data, $param = false)
    {
        if ($param) {
            var_dump('<pre>', $data, '<pre>');
        } else {
            var_dump($data);
        }
    }
}

// dd(ROOT);
// dd(DESTINATION);

// dd(APP . 'Cli' . EXT);

// include(APP. 'Cli'. EXT);

// include('src'.DIRECTORY_SEPARATOR.'Cli.php');
new Cli($argv);