#!/usr/bin/php
<?php

namespace Cli;

require('vendor/autoload.php');

define('EXT', '.php');
define('DS', DIRECTORY_SEPARATOR);

define('ROOT', dirname(__FILE__) . DS);
define('DESTINATION', dirname(__FILE__) . DS);
// define('DESTINATION', '../../App'.DS);
define('APP', ROOT . 'src' . DS);

/**
 * temp config for the framework path
 */
define('TEST', true);

// exit(DESTINATION);

/**
 * @param $data
 * @param bool $param
 */
if (!function_exists('dd')) {
    function dd($data, $param = false)
    {
        if ($param) {
            var_dump('<pre>', $data, '</pre>');
        } else {
            var_dump($data);
        }
        exit();
    }
}
/**
 * @param $data
 * @param bool $param
 */
if (!function_exists('ndd')) {
    function ndd($data, $param = false)
    {
        if ($param) {
            var_dump('<pre>', $data, '<pre>');
        } else {
            var_dump($data);
        }
    }
}

// dd(APP . 'Cli' . EXT);

include(APP. 'Cli'. EXT);

// include('src'.DIRECTORY_SEPARATOR.'Cli.php');
new Cli($argv);