#!/usr/bin/php
<?php
namespace Silver;
require('vendor/autoload.php');

define('EXT','.php');
define('DS',DIRECTORY_SEPARATOR);

define('ROOT', dirname(__FILE__).DS);
define('APP', ROOT.'src'.DS);

/**
 * @param $data
 * @param bool $param
 */
if (!function_exists('dd')) {
    function dd($data, $param = false)
    {
        if ($param) {
            var_dump('<pre>', $data, '</pre>');
        } else {
            var_dump($data);
        }
        exit();
    }
}
/**
 * @param $data
 * @param bool $param
 */
if (!function_exists('ndd')) {
    function ndd($data, $param = false)
    {
        if ($param) {
            var_dump('<pre>', $data, '<pre>');
        } else {
            var_dump($data);
        }
    }
}

// include('src'.DIRECTORY_SEPARATOR.'Cli.php');
echo new Cli($argv);